apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cli
  namespace: demo
  labels:
    name: redis-cli
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: redis-cli
  template:
    metadata:
      labels:
        name: redis-cli
    spec:
      containers:
      - name: redis
        image: redis:6.2.6-alpine
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "sleep 100000"
        ports:
        - containerPort: 6379